#!/usr/bin/env ruby

require 'thor'

class RVMBinary < Thor
  desc 'list', 'List available resources: virtual machines, binary builds or branches to test'
  # method_option :vm, aliases: 'os', desc: 'list available virtual machines'
  # method_option :binary, desc: 'list build binaries'
  # method_option :branch, desc: 'list available branches for testing'
  def list(resource)
    puts "#{resouce}"
  end
end

RVMBinary.start

# TODO
# ./run build $VERSION $OS1 $OS2 $OS3 ...
# ./run build $VERSION
# ./run test $BRANCH $OS
# ./run list (vm|binaries|branches)
# ./run upload
# ./run ssh $OS
