#!/usr/bin/env ruby

require 'yaml'

distributions = YAML::load_file('distributions.yml')

if ARGV.nil? || ARGV.length == 0 || ARGV[0] == "all"
  targets = distributions.keys
elsif %w( help --help -h ).include? ARGV[0]
  puts "Usage: ./run [help|list|<image>]"
  exit
elsif %w( list --list -l ).include? ARGV[0]
  puts distributions.keys
  exit
else
  targets = ARGV
end

if ( targets - distributions.keys ).length > 0
  $stderr.puts "Unknown command '#{ARGV*" "}'"
  puts "Usage: ./run [image]"
  exit 1
end

puts "### halting all"
system "vagrant halt"

targets.each do |target|
  puts "#### starting #{target}"
  system "vagrant up #{target}"
  system "vagrant halt #{target}"
  puts "#### stopping #{target}"
end

puts "### halting all"
system "vagrant halt"
puts "### haled all"
