#!/usr/bin/env ruby

require 'yaml'

distributions = YAML::load_file('distributions.yml')

if ARGV.nil? || ARGV.length == 0 || ARGV[0] == "all"
  targets = distributions.keys
elsif %w( help --help -h ).include? ARGV[0]
  puts "Usage: ./run [help|list|<image>]"
  exit
elsif %w( list --list -l ).include? ARGV[0]
  puts distributions.keys
  exit
else
  targets = ARGV
end

if ( targets - distributions.keys ).length > 0
  $stderr.puts "Unknown command '#{ARGV*" "}'"
  puts "Usage: ./run [image]"
  exit 1
end

puts "### halting all"
system "vagrant halt || vagrant halt --force"

Dir.mkdir "log/"

targets.each do |target|
  puts "#### starting #{target}"
  File.delete "log/#{target}.log"
  system "vagrant up #{target} 2>&1 | tee log/#{target}.log"
  system "vagrant halt #{target} 2>/dev/null || vagrant halt --force #{target}"
  puts "#### stopping #{target}"
end

puts "### halting all"
system "vagrant halt || vagrant halt --force"
puts "### haled all"
